"""
RFM Segmentation & Cohort Analysis
Runs against the SQLite database generated by data/generate_data.py
"""

import pandas as pd
import numpy as np
import sqlite3
import matplotlib.pyplot as plt
import seaborn as sns
import os

DB_PATH = "data/retail.db"
os.makedirs("data/outputs", exist_ok=True)

def load_data():
    conn = sqlite3.connect(DB_PATH)
    txn  = pd.read_sql("SELECT * FROM transactions", conn, parse_dates=["transaction_date"])
    cust = pd.read_sql("SELECT * FROM customers",    conn)
    conn.close()
    return txn, cust


# ── RFM Segmentation ─────────────────────────────────────────────────────────
def compute_rfm(txn: pd.DataFrame) -> pd.DataFrame:
    snapshot_date = txn["transaction_date"].max() + pd.Timedelta(days=1)

    rfm = txn.groupby("customer_id").agg(
        recency   = ("transaction_date", lambda x: (snapshot_date - x.max()).days),
        frequency = ("transaction_id",   "count"),
        monetary  = ("revenue",          "sum"),
    ).reset_index()

    rfm["r_score"] = pd.qcut(rfm["recency"],   5, labels=[5,4,3,2,1], duplicates="drop").astype(int)
    rfm["f_score"] = pd.qcut(rfm["frequency"], 5, labels=[1,2,3,4,5], duplicates="drop").astype(int)
    rfm["m_score"] = pd.qcut(rfm["monetary"],  5, labels=[1,2,3,4,5], duplicates="drop").astype(int)
    rfm["rfm_score"] = rfm["r_score"] + rfm["f_score"] + rfm["m_score"]

    def segment(score):
        if score >= 12: return "Champions"
        if score >= 9:  return "Loyal Customers"
        if score >= 6:  return "At Risk"
        return "Lost"

    rfm["segment"] = rfm["rfm_score"].apply(segment)
    return rfm


def plot_rfm(rfm: pd.DataFrame):
    seg_counts = rfm["segment"].value_counts()

    fig, axes = plt.subplots(1, 2, figsize=(14, 5))
    fig.suptitle("RFM Customer Segmentation", fontsize=15, fontweight="bold")

    # Pie chart
    colors = ["#2ecc71", "#3498db", "#e67e22", "#e74c3c"]
    axes[0].pie(seg_counts, labels=seg_counts.index, autopct="%1.1f%%",
                colors=colors, startangle=140)
    axes[0].set_title("Customer Segments (Count)")

    # Revenue by segment
    rev_by_seg = rfm.groupby("segment")["monetary"].sum().sort_values(ascending=False)
    axes[1].bar(rev_by_seg.index, rev_by_seg.values / 1e6, color=colors)
    axes[1].set_title("Revenue by Segment ($M)")
    axes[1].set_ylabel("Revenue ($ millions)")
    axes[1].tick_params(axis="x", rotation=15)

    plt.tight_layout()
    plt.savefig("data/outputs/rfm_segmentation.png", dpi=150, bbox_inches="tight")
    plt.close()
    print("✅ RFM chart saved → data/outputs/rfm_segmentation.png")
    return rfm


# ── Cohort Analysis ───────────────────────────────────────────────────────────
def compute_cohort(txn: pd.DataFrame) -> pd.DataFrame:
    txn = txn.copy()
    txn["order_month"]  = txn["transaction_date"].dt.to_period("M")
    first_orders        = txn.groupby("customer_id")["order_month"].min().rename("cohort_month")
    txn                 = txn.join(first_orders, on="customer_id")
    txn["cohort_index"] = (txn["order_month"] - txn["cohort_month"]).apply(lambda x: x.n)

    cohort_data = (
        txn.groupby(["cohort_month", "cohort_index"])["customer_id"]
        .nunique()
        .reset_index()
    )
    cohort_pivot = cohort_data.pivot(index="cohort_month", columns="cohort_index", values="customer_id")

    # Retention rates
    cohort_size    = cohort_pivot.iloc[:, 0]
    retention      = cohort_pivot.divide(cohort_size, axis=0).round(3) * 100
    return retention


def plot_cohort(retention: pd.DataFrame):
    fig, ax = plt.subplots(figsize=(16, 8))
    # Show only first 12 months and last 24 cohorts for readability
    plot_data = retention.iloc[-24:, :12]
    sns.heatmap(
        plot_data,
        annot=True, fmt=".0f",
        cmap="YlOrRd_r",
        ax=ax,
        linewidths=0.5,
        cbar_kws={"label": "Retention %"},
    )
    ax.set_title("Cohort Retention Rate (%)", fontsize=14, fontweight="bold")
    ax.set_xlabel("Months Since First Purchase")
    ax.set_ylabel("Cohort (Month of First Purchase)")
    plt.tight_layout()
    plt.savefig("data/outputs/cohort_analysis.png", dpi=150, bbox_inches="tight")
    plt.close()
    print("✅ Cohort chart saved → data/outputs/cohort_analysis.png")


# ── Main ──────────────────────────────────────────────────────────────────────
if __name__ == "__main__":
    txn, cust = load_data()

    print("Running RFM segmentation...")
    rfm = compute_rfm(txn)
    plot_rfm(rfm)
    rfm.to_csv("data/outputs/rfm_results.csv", index=False)

    print("\nRunning cohort analysis...")
    retention = compute_cohort(txn)
    plot_cohort(retention)
    retention.to_csv("data/outputs/cohort_retention.csv")

    print("\n📊 RFM Segment Summary:")
    print(rfm.groupby("segment").agg(
        customers=("customer_id","count"),
        avg_monetary=("monetary","mean"),
        total_revenue=("monetary","sum")
    ).round(2).to_string())
